### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by IncognitoBFD** [ekovegeance/DDOS#7]
I get this error **chmod: cannot access './ddos': No such file or directory** trying to run **chmod +x ./ddos**

**Comment by aravindvnair99** [comment]
@IncognitoBFD Clone the repository and run the `ddos` file

**Comment by aravindvnair99** [comment]
> @IncognitoBFD Clone the repository and run the `ddos` file

@ekovegeance This can be closed.
